/** Kalıp kimlikleri — kelime bankasından üretilebilen kalıplar (build:patterns) */
export const VOCAB_PATTERN_IDS = [
  "ich-bin",
  "ich-habe",
  "ich-moechte",
  "ich-kann",
  "ich-muss",
  "ich-will",
  "ich-brauche",
  "ich-esse",
  "ich-trinke",
  "ich-kaufe",
  "ich-lerne",
  "ich-arbeite",
  "ich-wohne-in",
  "ich-komme-aus",
  "ich-arbeite-als",
  "ich-spreche",
  "ich-verstehe",
  "das-ist",
  "ich-habe-keine",
  "wo-ist",
  "hast-du",
  "gibt-es",
  "was-ist",
  "wie-viel-kostet",
] as const;

export type VocabPatternId = (typeof VOCAB_PATTERN_IDS)[number];

export const PATTERN_LABEL_TR: Record<VocabPatternId, string> = {
  "ich-bin": "Ben …yım",
  "ich-habe": "Benim … var",
  "ich-moechte": "… istiyorum",
  "ich-kann": "… yapabilirim",
  "ich-muss": "… zorundayım",
  "ich-will": "… istiyorum",
  "ich-brauche": "… lazım",
  "ich-esse": "… yiyorum",
  "ich-trinke": "… içiyorum",
  "ich-kaufe": "… satın alıyorum",
  "ich-lerne": "… öğreniyorum",
  "ich-arbeite": "… çalışıyorum",
  "ich-wohne-in": "… oturuyorum",
  "ich-komme-aus": "… den geliyorum",
  "ich-arbeite-als": "… olarak çalışıyorum",
  "ich-spreche": "… konuşuyorum",
  "ich-verstehe": "… anlıyorum",
  "das-ist": "Bu …",
  "ich-habe-keine": "Benim … yok",
  "wo-ist": "… nerede?",
  "hast-du": "… var mı?",
  "gibt-es": "… var mı?",
  "was-ist": "… nedir?",
  "wie-viel-kostet": "… ne kadar?",
};
