import type { GrammarRuleRef } from "./types";

const MODAL_VERB_IDS = ["koennen", "muessen", "moechten", "wollen", "duerfen"] as const;

export const A1_GRAMMAR_MANIFEST: GrammarRuleRef[] = [
  {
    id: "artikel-definite",
    level: "A1",
    order: 1,
    titleTr: "Der / Die / Das",
    titleDe: "Artikel",
    sources: [
      { kind: "trainer-set", trainer: "artikel", setIds: ["der", "die", "das"] },
      { kind: "grammar-pack", sectionId: "artikel" },
    ],
    href: "/grundlagen/artikel",
  },
  {
    id: "pronouns",
    level: "A1",
    order: 2,
    titleTr: "Zamirler",
    titleDe: "Pronomen",
    sources: [
      { kind: "grammar-block", block: "pronouns" },
      { kind: "grammar-pack", sectionId: "pronouns" },
    ],
    href: "/grundlagen/grammar-pack",
    hrefQuery: "section=pronouns",
  },
  {
    id: "sein",
    level: "A1",
    order: 3,
    titleTr: "Sein (olmak)",
    sources: [
      { kind: "grammar-block", block: "sein" },
      { kind: "conjugation", verbIds: ["sein"] },
    ],
    href: "/grundlagen/conjugation",
  },
  {
    id: "haben",
    level: "A1",
    order: 4,
    titleTr: "Haben (sahip olmak)",
    sources: [
      { kind: "grammar-block", block: "haben" },
      { kind: "conjugation", verbIds: ["haben"] },
    ],
    href: "/grundlagen/conjugation",
  },
  {
    id: "word-order-svo",
    level: "A1",
    order: 5,
    titleTr: "Düz cümle (SVO)",
    titleDe: "Wortstellung",
    sources: [{ kind: "word-order", sectionIds: ["statement"] }],
    href: "/grundlagen/word-order",
  },
  {
    id: "verbs-regular",
    level: "A1",
    order: 6,
    titleTr: "Fiil çekimi",
    titleDe: "Verbkonjugation",
    sources: [
      { kind: "grammar-block", block: "regularRule" },
      { kind: "grammar-block", block: "irregularRule" },
      { kind: "grammar-pack", sectionId: "verbs" },
      {
        kind: "conjugation",
        verbIds: undefined,
      },
    ],
    href: "/grundlagen/conjugation",
  },
  {
    id: "w-fragen",
    level: "A1",
    order: 7,
    titleTr: "W-Fragen",
    sources: [
      { kind: "fragewoerter" },
      { kind: "word-order", sectionIds: ["w_question"] },
      { kind: "grammar-pack", sectionId: "wFragen" },
    ],
    href: "/grundlagen/grammar-pack",
    hrefQuery: "section=wFragen",
  },
  {
    id: "ja-nein",
    level: "A1",
    order: 8,
    titleTr: "Ja/Nein soruları",
    sources: [
      { kind: "grammar-block", block: "jaNein" },
      { kind: "word-order", sectionIds: ["yes_no"] },
      { kind: "grammar-pack", sectionId: "jaNein" },
    ],
    href: "/grundlagen/word-order",
  },
  {
    id: "modalverben",
    level: "A1",
    order: 9,
    titleTr: "Modalverben",
    sources: [
      { kind: "grammar-block", block: "modals" },
      { kind: "conjugation", verbIds: [...MODAL_VERB_IDS] },
      { kind: "grammar-pack", sectionId: "modalverben" },
    ],
    href: "/grundlagen/grammar-pack",
    hrefQuery: "section=modalverben",
  },
  {
    id: "akkusativ",
    level: "A1",
    order: 10,
    titleTr: "Akkusativ",
    sources: [
      { kind: "grammar-block", block: "akkusativ" },
      { kind: "grammar-pack", sectionId: "akkusativ" },
      { kind: "trainer-set", trainer: "artikel", setIds: ["ein"] },
    ],
    href: "/grundlagen/grammar-pack",
    hrefQuery: "section=akkusativ",
  },
  {
    id: "possessives",
    level: "A1",
    order: 11,
    titleTr: "Sahiplik zamirleri",
    sources: [
      { kind: "trainer-set", trainer: "possessives" },
      { kind: "grammar-pack", sectionId: "possessiv" },
    ],
    href: "/grundlagen/possessives",
  },
  {
    id: "negation",
    level: "A1",
    order: 12,
    titleTr: "Olumsuzluk (nicht / kein)",
    sources: [
      { kind: "grammar-block", block: "negation" },
      { kind: "trainer-set", trainer: "negation" },
      { kind: "grammar-pack", sectionId: "negation" },
    ],
    href: "/grundlagen/negation",
  },
  {
    id: "trennbar",
    level: "A1",
    order: 13,
    titleTr: "Trennbare Verben",
    sources: [
      { kind: "grammar-block", block: "trennbareVerben" },
      { kind: "grammar-pack", sectionId: "trennbar" },
    ],
    href: "/grundlagen/grammar-pack",
    hrefQuery: "section=trennbar",
  },
  {
    id: "dativ",
    level: "A1",
    order: 14,
    titleTr: "Dativ",
    sources: [
      { kind: "grammar-block", block: "dativBasics" },
      { kind: "trainer-set", trainer: "dativ" },
      { kind: "grammar-pack", sectionId: "dativ" },
    ],
    href: "/grundlagen/dativ",
  },
  {
    id: "praepositionen",
    level: "A1",
    order: 15,
    titleTr: "Edatlar",
    sources: [
      { kind: "trainer-set", trainer: "prepositions" },
      { kind: "grammar-pack", sectionId: "praepositionen" },
    ],
    href: "/grundlagen/prepositions",
  },
  {
    id: "ein-artikel",
    level: "A1",
    order: 16,
    titleTr: "ein / eine",
    sources: [
      { kind: "trainer-set", trainer: "artikel", setIds: ["ein"] },
      { kind: "grammar-pack", sectionId: "ein-artikel" },
    ],
    href: "/grundlagen/artikel",
  },
  {
    id: "plural",
    level: "A1",
    order: 17,
    titleTr: "Çoğul",
    titleDe: "Plural",
    sources: [
      { kind: "grammar-block", block: "plural" },
      { kind: "trainer-set", trainer: "artikel", setIds: ["plural"] },
      { kind: "grammar-pack", sectionId: "plural" },
    ],
    href: "/grundlagen/grammar-pack",
    hrefQuery: "section=plural",
  },
  {
    id: "konjunktionen",
    level: "A1",
    order: 18,
    titleTr: "Bağlaçlar",
    sources: [
      { kind: "grammar-block", block: "konjunktionen" },
      { kind: "word-order", sectionIds: ["conjunction"] },
      { kind: "grammar-pack", sectionId: "konjunktionen" },
    ],
    href: "/grundlagen/grammar-pack",
    hrefQuery: "section=konjunktionen",
  },
  {
    id: "imperativ",
    level: "A1",
    order: 19,
    titleTr: "Imperativ",
    sources: [
      { kind: "grammar-block", block: "imperativ" },
      { kind: "grammar-pack", sectionId: "imperativ" },
    ],
    href: "/grundlagen/grammar-pack",
    hrefQuery: "section=imperativ",
  },
  {
    id: "patterns",
    level: "A1",
    order: 20,
    titleTr: "Cümle kalıpları",
    sources: [{ kind: "grammar-block", block: "patterns" }, { kind: "patterns" }],
    href: "/grundlagen/patterns",
  },
  {
    id: "perfekt-intro",
    level: "A1",
    order: 21,
    titleTr: "Perfekt tanıma",
    sources: [
      { kind: "grammar-block", block: "perfektIntro" },
      { kind: "grammar-pack", sectionId: "perfekt-intro" },
    ],
    href: "/grundlagen/grammar-pack",
    hrefQuery: "section=perfekt-intro",
  },
  {
    id: "word-order-mixed",
    level: "A1",
    order: 22,
    titleTr: "Karışık kelime sırası",
    sources: [
      { kind: "word-order", sectionIds: ["compare"], includeMega: true },
    ],
    href: "/grundlagen/word-order",
  },
  {
    id: "satz-builder",
    level: "A1",
    order: 23,
    titleTr: "Cümle kur",
    sources: [{ kind: "satz" }],
    href: "/grundlagen/satz",
  },
  {
    id: "grammar-reference",
    level: "A1",
    order: 24,
    titleTr: "Gramer referans",
    sources: [],
    href: "/grundlagen/grammar",
  },
];

export const A2_GRAMMAR_MANIFEST: GrammarRuleRef[] = [
  {
    id: "perfekt",
    level: "A2",
    order: 1,
    titleTr: "Perfekt",
    sources: [{ kind: "a2-section", sectionId: "perfekt" }],
    href: "/grundlagen/roadmap",
  },
  {
    id: "dativ-a2",
    level: "A2",
    order: 2,
    titleTr: "Dativ (A2 pekiştirme)",
    sources: [{ kind: "a2-section", sectionId: "dativ-intro" }],
    href: "/grundlagen/dativ",
  },
  {
    id: "nebensatz",
    level: "A2",
    order: 3,
    titleTr: "Basit Nebensatz (weil / dass)",
    sources: [{ kind: "a2-section", sectionId: "nebensatz" }],
    href: "/grundlagen/roadmap",
  },
];

export const B1_PLACEHOLDER_IDS = ["relativsaetze", "nebensatz-b1", "konjunktiv"] as const;
