/** A2 yeni kelimeler — [word, article, plural, tr, ru, example_de, example_tr, tags[]] */

function w(word, article, plural, tr, ru, exDe, exTr, tags = ["a2"]) {
  return [word, article, plural, tr, ru, exDe, exTr, tags];
}

export const A2_NEW_WORDS = {
  Seyahat: [
    w("der Bahnhof", "der", "Bahnhöfe", "tren istasyonu", "вокзал", "Der Bahnhof ist groß.", "İstasyon büyük.", ["travel"]),
    w("die Fahrkarte", "die", "Fahrkarten", "bilet", "билет", "Ich kaufe eine Fahrkarte.", "Bilet alıyorum.", ["travel"]),
    w("der Anschluss", "der", "Anschlüsse", "aktarma", "пересадка", "Ich habe einen Anschluss in München.", "Münih'te aktarmam var.", ["travel"]),
    w("die Verspätung", "die", "Verspätungen", "gecikme", "задержка", "Der Zug hat Verspätung.", "Tren gecikmeli.", ["travel"]),
    w("abfahren", null, null, "hareket etmek", "отправляться", "Der Zug fährt um acht ab.", "Tren saat sekizde kalkıyor.", ["travel", "verb"]),
    w("ankommen", null, null, "varmak", "прибывать", "Wir kommen um zehn an.", "Saat onda varıyoruz.", ["travel", "verb"]),
    w("die Reise", "die", "Reisen", "seyahat", "поездка", "Die Reise war schön.", "Seyahat güzeldi.", ["travel"]),
    w("der Koffer", "der", "Koffer", "bavul", "чемодан", "Mein Koffer ist schwer.", "Bavulum ağır.", ["travel"]),
    w("einsteigen", null, null, "binmek", "садиться", "Bitte schnell einsteigen!", "Lütfen hızlı binin!", ["travel", "verb"]),
    w("aussteigen", null, null, "inmek", "выходить", "An der nächsten Haltestelle steige ich aus.", "Bir sonraki durakta iniyorum.", ["travel", "verb"]),
  ],
  "Alışveriş & Hizmetler": [
    w("die Quittung", "die", "Quittungen", "fiş", "чек", "Kann ich eine Quittung haben?", "Fiş alabilir miyim?", ["shopping"]),
    w("umtauschen", null, null, "değiştirmek", "обменивать", "Ich möchte das Hemd umtauschen.", "Gömleği değiştirmek istiyorum.", ["shopping", "verb"]),
    w("die Größe", "die", "Größen", "beden", "размер", "Welche Größe haben Sie?", "Hangi bedeniniz var?", ["shopping"]),
    w("die Reparatur", "die", "Reparaturen", "tamir", "ремонт", "Die Reparatur dauert zwei Tage.", "Tamir iki gün sürer.", ["shopping"]),
    w("die Garantie", "die", "Garantien", "garanti", "гарантия", "Die Garantie ist zwei Jahre.", "Garanti iki yıl.", ["shopping"]),
    w("bestellen", null, null, "sipariş etmek", "заказывать", "Ich bestelle eine Pizza.", "Pizza sipariş ediyorum.", ["shopping", "verb"]),
    w("liefern", null, null, "teslim etmek", "доставлять", "Sie liefern bis morgen.", "Yarın kadar teslim ediyorlar.", ["shopping", "verb"]),
    w("der Rabatt", "der", "Rabatte", "indirim", "скидка", "Heute gibt es zehn Prozent Rabatt.", "Bugün yüzde on indirim var.", ["shopping"]),
    w("die Kasse", "die", "Kassen", "kasa", "касса", "An der Kasse bitte.", "Kasada lütfen.", ["shopping"]),
    w("bar bezahlen", null, null, "nakit ödemek", "платить наличными", "Kann ich bar bezahlen?", "Nakit ödeyebilir miyim?", ["shopping"]),
  ],
  Sağlık: [
    w("das Rezept", "das", "Rezepte", "reçete", "рецепт", "Der Arzt schreibt ein Rezept.", "Doktor reçete yazıyor.", ["health"]),
    w("die Apotheke", "die", "Apotheken", "eczane", "аптека", "Die Apotheke ist neben dem Krankenhaus.", "Eczane hastanenin yanında.", ["health"]),
    w("die Untersuchung", "die", "Untersuchungen", "muayene", "осмотр", "Die Untersuchung dauert zwanzig Minuten.", "Muayene yirmi dakika sürer.", ["health"]),
    w("sich erkälten", null, null, "soğuk algınlığına yakalanmak", "простудиться", "Ich habe mich erkältet.", "Soğuk algınlığına yakalandım.", ["health", "verb"]),
    w("die Tablette", "die", "Tabletten", "tablet", "таблетка", "Nehmen Sie drei Tabletten täglich.", "Günde üç tablet alın.", ["health"]),
    w("der Termin", "der", "Termine", "randevu", "приём", "Mein Termin ist um vierzehn Uhr.", "Randevum saat on dört.", ["health"]),
    w("die Versicherung", "die", "Versicherungen", "sigorta", "страховка", "Haben Sie eine Krankenversicherung?", "Sağlık sigortanız var mı?", ["health"]),
    w("sich fühlen", null, null, "hissetmek", "чувствовать", "Ich fühle mich besser.", "Kendimi daha iyi hissediyorum.", ["health", "verb"]),
    w("die Schmerzen", "die", "Schmerzen", "ağrılar", "боли", "Ich habe Schmerzen im Rücken.", "Sırtımda ağrı var.", ["health"]),
    w("die Impfung", "die", "Impfungen", "aşı", "прививка", "Die Impfung ist wichtig.", "Aşı önemli.", ["health"]),
  ],
  "İş & Kariyer": [
    w("das Vorstellungsgespräch", "das", "Vorstellungsgespräche", "iş görüşmesi", "собеседование", "Das Vorstellungsgespräch ist morgen.", "İş görüşmesi yarın.", ["work"]),
    w("der Lebenslauf", "der", "Lebensläufe", "özgeçmiş", "резюме", "Bitte schicken Sie Ihren Lebenslauf.", "Lütfen özgeçmişinizi gönderin.", ["work"]),
    w("die Bewerbung", "die", "Bewerbungen", "başvuru", "заявление", "Meine Bewerbung ist fertig.", "Başvurum hazır.", ["work"]),
    w("der Kollege", "der", "Kollegen", "iş arkadaşı (erkek)", "коллега", "Mein Kollege ist nett.", "İş arkadaşım nazik.", ["work"]),
    w("die Kollegin", "die", "Kolleginnen", "iş arkadaşı (kadın)", "коллега", "Meine Kollegin hilft mir.", "İş arkadaşım bana yardım ediyor.", ["work"]),
    w("die Überstunde", "die", "Überstunden", "fazla mesai", "сверхурочные", "Ich mache heute Überstunden.", "Bugün fazla mesai yapıyorum.", ["work"]),
    w("kündigen", null, null, "istifa etmek / feshetmek", "увольняться", "Er hat gekündigt.", "İstifa etti.", ["work", "verb"]),
    w("einstellen", null, null, "işe almak", "нанимать", "Die Firma stellt neue Leute ein.", "Firma yeni insanlar işe alıyor.", ["work", "verb"]),
    w("der Vertrag", "der", "Verträge", "sözleşme", "договор", "Der Vertrag ist unterschrieben.", "Sözleşme imzalandı.", ["work"]),
    w("die Erfahrung", "die", "Erfahrungen", "deneyim", "опыт", "Ich habe viel Erfahrung.", "Çok deneyimim var.", ["work"]),
  ],
  "Günlük rutin": [
    w("frühstücken", null, null, "kahvaltı yapmak", "завтракать", "Ich frühstücke um sieben.", "Saat yedide kahvaltı yapıyorum.", ["routine", "verb"]),
    w("sich anziehen", null, null, "giyinmek", "одеваться", "Ich ziehe mich schnell an.", "Hızlı giyiniyorum.", ["routine", "verb"]),
    w("putzen", null, null, "temizlemek", "убирать", "Am Samstag putze ich die Wohnung.", "Cumartesi daireyi temizliyorum.", ["routine", "verb"]),
    w("die Wäsche", "die", null, "çamaşır", "бельё", "Ich wasche die Wäsche.", "Çamaşır yıkıyorum.", ["routine"]),
    w("einkaufen gehen", null, null, "alışverişe gitmek", "ходить за покупками", "Am Abend gehe ich einkaufen.", "Akşam alışverişe gidiyorum.", ["routine"]),
    w("sich ausruhen", null, null, "dinlenmek", "отдыхать", "Nach der Arbeit ruhe ich mich aus.", "İşten sonra dinleniyorum.", ["routine", "verb"]),
    w("aufräumen", null, null, "toplamak / düzenlemek", "убирать", "Die Kinder räumen ihr Zimmer auf.", "Çocuklar odalarını topluyor.", ["routine", "verb"]),
    w("die Pause", "die", "Pausen", "mola", "перерыв", "In der Pause trinke ich Kaffee.", "Molada kahve içiyorum.", ["routine"]),
    w("pünktlich", null, null, "dakik", "пунктуальный", "Er ist immer pünktlich.", "O her zaman dakik.", ["routine"]),
    w("verschlafen", null, null, "uyuyakalmak", "проспать", "Ich habe heute verschlafen.", "Bugün uyuyakaldım.", ["routine", "verb"]),
  ],
  "Hava & Doğa": [
    w("regnen", null, null, "yağmur yağmak", "идти (дождь)", "Es regnet heute.", "Bugün yağmur yağıyor.", ["weather", "verb"]),
    w("schneien", null, null, "kar yağmak", "идти (снег)", "Im Winter schneit es oft.", "Kışın sık kar yağar.", ["weather", "verb"]),
    w("die Sonne", "die", null, "güneş", "солнце", "Die Sonne scheint.", "Güneş parlıyor.", ["weather"]),
    w("bewölkt", null, null, "bulutlu", "облачно", "Heute ist es bewölkt.", "Bugün hava bulutlu.", ["weather"]),
    w("der Wind", "der", "Winde", "rüzgar", "ветер", "Der Wind ist stark.", "Rüzgar kuvvetli.", ["weather"]),
    w("warm", null, null, "ılık / sıcak", "тёплый", "Im Sommer ist es warm.", "Yazın hava sıcak.", ["weather"]),
    w("kalt", null, null, "soğuk", "холодный", "Im Winter ist es kalt.", "Kışın hava soğuk.", ["weather"]),
    w("der Wald", "der", "Wälder", "orman", "лес", "Wir gehen im Wald spazieren.", "Ormanda yürüyoruz.", ["nature"]),
    w("der See", "der", "Seen", "göl", "озеро", "Der See ist sehr schön.", "Göl çok güzel.", ["nature"]),
    w("die Landschaft", "die", "Landschaften", "manzara", "пейзаж", "Die Landschaft ist wunderbar.", "Manzara harika.", ["nature"]),
  ],
  Duygular: [
    w("glücklich", null, null, "mutlu", "счастливый", "Ich bin heute glücklich.", "Bugün mutluyum.", ["emotion"]),
    w("traurig", null, null, "üzgün", "грустный", "Warum bist du traurig?", "Neden üzgünsün?", ["emotion"]),
    w("nervös", null, null, "gergin", "нервный", "Vor der Prüfung bin ich nervös.", "Sınavdan önce gerginim.", ["emotion"]),
    w("stolz", null, null, "gururlu", "гордый", "Ich bin stolz auf dich.", "Seninle gurur duyuyorum.", ["emotion"]),
    w("sich freuen", null, null, "sevinmek", "радоваться", "Ich freue mich auf das Wochenende.", "Hafta sonunu dört gözle bekliyorum.", ["emotion", "verb"]),
    w("sich ärgern", null, null, "sinirlenmek", "злиться", "Er ärgert sich über den Lärm.", "Gürültüye sinirleniyor.", ["emotion", "verb"]),
    w("die Freude", "die", null, "sevinç", "радость", "Das ist eine große Freude.", "Bu büyük bir sevinç.", ["emotion"]),
    w("die Angst", "die", "Ängste", "korku", "страх", "Ich habe Angst vor Spinnen.", "Örümceklerden korkuyorum.", ["emotion"]),
    w("überrascht", null, null, "şaşırmış", "удивлённый", "Ich bin überrascht.", "Şaşırdım.", ["emotion"]),
    w("verliebt", null, null, "aşık", "влюблённый", "Er ist verliebt.", "Aşık.", ["emotion"]),
  ],
  "Geçmiş zaman": [
    w("gestern", null, null, "dün", "вчера", "Gestern war ich im Kino.", "Dün sinemadaydım.", ["past"]),
    w("letzte Woche", null, null, "geçen hafta", "на прошлой неделе", "Letzte Woche habe ich gearbeitet.", "Geçen hafta çalıştım.", ["past"]),
    w("schon", null, null, "zaten / -miş", "уже", "Ich habe schon gegessen.", "Zaten yemek yedim.", ["past"]),
    w("noch nicht", null, null, "henüz değil", "ещё не", "Ich habe noch nicht geantwortet.", "Henüz cevap vermedim.", ["past"]),
    w("gekauft", null, null, "satın alınmış", "купленный", "Ich habe Brot gekauft.", "Ekmek satın aldım.", ["past", "perfekt"]),
    w("gemacht", null, null, "yapılmış", "сделанный", "Was hast du gemacht?", "Ne yaptın?", ["past", "perfekt"]),
    w("gegangen", null, null, "gitmiş", "ушедший", "Wir sind spazieren gegangen.", "Yürüyüşe gittik.", ["past", "perfekt"]),
    w("gekommen", null, null, "gelmiş", "пришедший", "Er ist spät gekommen.", "Geç geldi.", ["past", "perfekt"]),
    w("gesehen", null, null, "görmüş", "видевший", "Hast du den Film gesehen?", "Filmi gördün mü?", ["past", "perfekt"]),
    w("gewesen", null, null, "olmuş / bulunmuş", "бывший", "Ich bin in Berlin gewesen.", "Berlin'de bulundum.", ["past", "perfekt"]),
  ],
};
